table Clients
	lineageTag: 59cc0dd1-bd49-4644-b26c-c1bb55c5d09a

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2cd74f92-d8d7-4d3a-b390-8b8896f3a5bb
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = User

	column Genre
		dataType: string
		lineageTag: 05c5f43e-bcd6-49ba-94a2-a2d87549c99e
		summarizeBy: none
		sourceColumn: Genre

		annotation SummarizationSetBy = User

	column 'Date de naissance'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f6ad20c4-63a0-4184-8dbc-c82bff586782
		summarizeBy: none
		sourceColumn: Date de naissance

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'Ville du client'
		dataType: string
		lineageTag: 53fba5c8-9b97-49aa-9ce6-a354f90ced37
		summarizeBy: none
		sourceColumn: Ville du client

		annotation SummarizationSetBy = User

	column 'Région du client'
		dataType: string
		lineageTag: ef3e4f39-fb61-4a94-8a2c-a66ba2153173
		summarizeBy: none
		sourceColumn: Région du client

		annotation SummarizationSetBy = User

	column 'Pays du client'
		dataType: string
		lineageTag: 3f50dc38-8e84-4fce-a650-47079b610253
		summarizeBy: none
		sourceColumn: Pays du client

		annotation SummarizationSetBy = User

	partition Clients = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "customer.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"CustomerKey", Int64.Type}, {"GeoAreaKey", Int64.Type}, {"StartDT", type date}, {"EndDT", type date}, {"Continent", type text}, {"Gender", type text}, {"Title", type text}, {"GivenName", type text}, {"MiddleInitial", type text}, {"Surname", type text}, {"StreetAddress", type text}, {"City", type text}, {"State", type text}, {"StateFull", type text}, {"ZipCode", type text}, {"Country", type text}, {"CountryFull", type text}, {"Birthday", type date}, {"Age", Int64.Type}, {"Occupation", type text}, {"Company", type text}, {"Vehicle", type text}, {"Latitude", type number}, {"Longitude", type number}}),
				    // Minimisation des données : seules les colonnes utiles à l'analyse sont conservées
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Type modifié",{"CustomerKey", "Gender", "Birthday", "City", "StateFull", "CountryFull"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Autres colonnes supprimées",{{"Gender", "Genre"}, {"Birthday", "Date de naissance"}, {"City", "Ville du client"}, {"StateFull", "Région du client"}, {"CountryFull", "Pays du client"}}),
				    #"Genre homme" = Table.ReplaceValue(#"Colonnes renommées","male","Homme",Replacer.ReplaceValue,{"Genre"}),
				    #"Genre femme" = Table.ReplaceValue(#"Genre homme","female","Femme",Replacer.ReplaceValue,{"Genre"})
				in
				    #"Genre femme"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

