table Magasins
	lineageTag: 0f07807f-0485-426b-9631-cd4b67723202

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 71cf961f-5054-4efa-9102-b293fbd059c6
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = User

	column Magasin
		dataType: string
		lineageTag: e865e578-4169-4da8-a3f2-98774cb0d9dd
		summarizeBy: none
		sourceColumn: Magasin

		annotation SummarizationSetBy = User

	column Canal
		dataType: string
		lineageTag: d882a987-f17e-4ad9-baf8-92e84fd9c85b
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = User

	column 'Pays du magasin'
		dataType: string
		lineageTag: 0cbba56a-a645-4a16-ad09-37192f897d45
		summarizeBy: none
		sourceColumn: Pays du magasin

		annotation SummarizationSetBy = User

	column 'Région du magasin'
		dataType: string
		lineageTag: 01db3c5a-fe99-49d5-9c0d-d7ea6e89d6d5
		summarizeBy: none
		sourceColumn: Région du magasin

		annotation SummarizationSetBy = User

	column 'Date d''ouverture'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f4b44a96-1c64-40c8-9b32-c4da2481d2d4
		summarizeBy: none
		sourceColumn: Date d'ouverture

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'Date de fermeture'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: dddfefac-056d-491d-a632-990deae09240
		summarizeBy: none
		sourceColumn: Date de fermeture

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'Surface (m²)'
		dataType: int64
		formatString: #,0
		lineageTag: 4c522343-6905-4500-9f91-5767e53a24f2
		summarizeBy: none
		sourceColumn: Surface (m²)

		annotation SummarizationSetBy = User

	column Statut
		dataType: string
		lineageTag: d686ce5f-f5d7-4a6f-bb5d-2e75ca71f666
		summarizeBy: none
		sourceColumn: Statut

		annotation SummarizationSetBy = User

	partition Magasins = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "store.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"StoreKey", Int64.Type}, {"StoreCode", Int64.Type}, {"GeoAreaKey", Int64.Type}, {"CountryCode", type text}, {"CountryName", type text}, {"State", type text}, {"OpenDate", type date}, {"CloseDate", type date}, {"Description", type text}, {"SquareMeters", Int64.Type}, {"Status", type text}}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Type modifié",{"StoreKey", "CountryName", "State", "OpenDate", "CloseDate", "SquareMeters", "Status"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Autres colonnes supprimées",{{"CountryName", "Pays du magasin"}, {"State", "Région du magasin"}, {"OpenDate", "Date d'ouverture"}, {"CloseDate", "Date de fermeture"}, {"SquareMeters", "Surface (m²)"}, {"Status", "Statut"}}),
				    #"Statut fermé" = Table.ReplaceValue(#"Colonnes renommées","Closed","Fermé",Replacer.ReplaceValue,{"Statut"}),
				    #"Statut restructuré" = Table.ReplaceValue(#"Statut fermé","Restructured","Restructuré",Replacer.ReplaceValue,{"Statut"}),
				    #"Statut ouvert" = Table.ReplaceValue(#"Statut restructuré","","Ouvert",Replacer.ReplaceValue,{"Statut"}),
				    #"Online traduit" = Table.ReplaceValue(#"Statut ouvert","Online","En ligne",Replacer.ReplaceValue,{"Pays du magasin", "Région du magasin"}),
				    #"Canal ajouté" = Table.AddColumn(#"Online traduit", "Canal", each if [StoreKey] = 999999 then "En ligne" else "Magasin physique", type text),
				    // Plusieurs magasins restructurés partagent la même région : l'année d'ouverture rend le libellé unique
				    #"Libellé magasin ajouté" = Table.AddColumn(#"Canal ajouté", "Magasin", each if [StoreKey] = 999999 then "Boutique en ligne" else [Région du magasin] & " (" & Text.From(Date.Year([#"Date d'ouverture"])) & ")", type text)
				in
				    #"Libellé magasin ajouté"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

