table Produits
	lineageTag: 885a8beb-6030-4d7d-9c50-1017a8029aac

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c5be3d5-a10a-493d-a7c6-b5f940cc2fd1
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = User

	column Produit
		dataType: string
		lineageTag: 482e442b-1d60-4a0f-bff7-1f68e04da423
		summarizeBy: none
		sourceColumn: Produit

		annotation SummarizationSetBy = User

	column Marque
		dataType: string
		lineageTag: c2c188c7-7acd-4161-b11e-27a0c7405d7d
		summarizeBy: none
		sourceColumn: Marque

		annotation SummarizationSetBy = User

	column Catégorie
		dataType: string
		lineageTag: 64505395-7da7-4d7a-898b-13a14b5b7638
		summarizeBy: none
		sourceColumn: Catégorie

		annotation SummarizationSetBy = User

	column Sous-catégorie
		dataType: string
		lineageTag: 453f8b41-b632-4143-959b-9966b7185d3e
		summarizeBy: none
		sourceColumn: Sous-catégorie

		annotation SummarizationSetBy = User

	partition Produits = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "product.csv"),[Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ProductCode", type text}, {"ProductKey", Int64.Type}, {"ProductName", type text}, {"Manufacturer", type text}, {"Brand", type text}, {"Color", type text}, {"WeightUnit", type text}, {"Weight", type number}, {"Cost", type number}, {"Price", type number}, {"CategoryKey", Int64.Type}, {"CategoryName", type text}, {"SubCategoryKey", Int64.Type}, {"SubCategoryName", type text}}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Type modifié",{"ProductKey", "ProductName", "Brand", "CategoryName", "SubCategoryName"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Autres colonnes supprimées",{{"ProductName", "Produit"}, {"Brand", "Marque"}, {"CategoryName", "Catégorie"}, {"SubCategoryName", "Sous-catégorie"}})
				in
				    #"Colonnes renommées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

