table Produits
	lineageTag: 5ad0e10e-afb8-4eb7-aa92-2a1d39a94697

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: c09240d4-4b83-4afb-b055-76dccbafff4a
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductCode
		dataType: string
		lineageTag: 7afb5302-50bf-45e2-a02b-ae368628deb8
		summarizeBy: none
		sourceColumn: ProductCode

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: d4fdc4cf-5a93-4ada-a785-c84ede535e04
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: 7edeb13a-b172-41b7-af0d-e74528d4ef2a
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: a5edd8be-3bd0-4298-b6a0-08cc6a86d594
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 219264f2-47ca-48f8-bc5f-320b0c925bd4
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column WeightUnit
		dataType: string
		lineageTag: a6361b51-9314-4b2f-aeb8-f2a6b988a8e4
		summarizeBy: none
		sourceColumn: WeightUnit

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 77433f45-e023-46b1-8b88-75ff25ec751c
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost
		dataType: double
		lineageTag: ec969136-8820-4f9c-96b4-80973847582a
		summarizeBy: none
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price
		dataType: double
		lineageTag: 846ca101-784d-4d97-a694-7d37e497769f
		summarizeBy: none
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 099e631a-e13c-4b39-a636-621345784e41
		summarizeBy: none
		sourceColumn: CategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: e14d2630-91b8-45b2-b184-27bc66ac6135
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column SubCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: e311b9f2-2553-4957-a669-e209e4767735
		summarizeBy: none
		sourceColumn: SubCategoryKey

		annotation SummarizationSetBy = Automatic

	column SubCategoryName
		dataType: string
		lineageTag: e8367171-a3be-45e3-8292-3e061c97f200
		summarizeBy: none
		sourceColumn: SubCategoryName

		annotation SummarizationSetBy = Automatic

	partition Produits = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents(CheminDonnees & "product.csv"),[Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				  #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ProductCode", type text}, {"ProductKey", Int64.Type}, {"ProductName", type text}, {"Manufacturer", type text}, {"Brand", type text}, {"Color", type text}, {"WeightUnit", type text}, {"Weight", type number}, {"Cost", type number}, {"Price", type number}, {"CategoryKey", Int64.Type}, {"CategoryName", type text}, {"SubCategoryKey", Int64.Type}, {"SubCategoryName", type text}})
				in
				  #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

