table Ventes
	lineageTag: 03f6a82c-4388-4d1c-b39e-6ca7c857fb97

	column OrderKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2eed229b-9613-4b48-a7c4-ef61b24e0729
		summarizeBy: none
		sourceColumn: OrderKey

		annotation SummarizationSetBy = User

	column 'Date de commande'
		dataType: dateTime
		isHidden
		formatString: dd/mm/yyyy
		lineageTag: ba8b7045-5a63-4056-ac34-219ed7512412
		summarizeBy: none
		sourceColumn: Date de commande

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'Date de livraison'
		dataType: dateTime
		isHidden
		formatString: dd/mm/yyyy
		lineageTag: cd0dbcc9-8069-42ae-a497-eefd376a844b
		summarizeBy: none
		sourceColumn: Date de livraison

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 68061b1b-d556-48ed-9566-6e51e8a7383c
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = User

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8e8d93fb-f2be-43b9-bf81-86ce234962ca
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = User

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c37ba30-feee-40b1-8f10-ea7d537373cd
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = User

	column Quantité
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 4f2cb9a9-e6d2-4f08-8a68-347ec47106f1
		summarizeBy: none
		sourceColumn: Quantité

		annotation SummarizationSetBy = User

	column 'Prix unitaire'
		dataType: double
		isHidden
		formatString: \$#,0.00
		lineageTag: 4f31c552-d371-46de-ba90-0c70bc866254
		summarizeBy: none
		sourceColumn: Prix unitaire

		annotation SummarizationSetBy = User

	column 'Prix net'
		dataType: double
		isHidden
		formatString: \$#,0.00
		lineageTag: eebd3a50-a795-4c69-b154-97a5c461f9e1
		summarizeBy: none
		sourceColumn: Prix net

		annotation SummarizationSetBy = User

	column 'Délai de livraison (jours)'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7cd95896-de41-4d35-9891-b5614bf77e29
		summarizeBy: none
		sourceColumn: Délai de livraison (jours)

		annotation SummarizationSetBy = User

	column 'Coût unitaire'
		dataType: double
		isHidden
		formatString: \$#,0.00
		lineageTag: e401b06e-c394-4d29-94b9-2773c80a5d50
		summarizeBy: none
		sourceColumn: Coût unitaire

		annotation SummarizationSetBy = User

	partition Ventes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "sales.csv"),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"OrderKey", Int64.Type}, {"LineNumber", Int64.Type}, {"OrderDate", type date}, {"DeliveryDate", type date}, {"CustomerKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"NetPrice", type number}, {"UnitCost", type number}, {"CurrencyCode", type text}, {"ExchangeRate", type number}}),
				    #"Autres colonnes supprimées" = Table.SelectColumns(#"Type modifié",{"OrderKey", "OrderDate", "DeliveryDate", "CustomerKey", "StoreKey", "ProductKey", "Quantity", "UnitPrice", "NetPrice", "UnitCost"}),
				    #"Colonnes renommées" = Table.RenameColumns(#"Autres colonnes supprimées",{{"OrderDate", "Date de commande"}, {"DeliveryDate", "Date de livraison"}, {"Quantity", "Quantité"}, {"UnitPrice", "Prix unitaire"}, {"NetPrice", "Prix net"}, {"UnitCost", "Coût unitaire"}}),
				    #"Personnalisée ajoutée" = Table.AddColumn(#"Colonnes renommées", "Délai de livraison (jours)", each Duration.Days([Date de livraison] - [Date de commande]), Int64.Type)
				in
				    #"Personnalisée ajoutée"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

